//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_USUARIO
    {
        public int CODUSU { get; set; }
        public string NOMUSU { get; set; }
        public string PASUSU { get; set; }
        public string NOMPERUSU { get; set; }
        public string APEPERUSU { get; set; }
        public string DNIUSU { get; set; }
        public Nullable<int> TIPCARUSU { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODENT { get; set; }
        public Nullable<int> CODPER { get; set; }
        public string CORREOUSER { get; set; }
    }
}
