//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_AUDITORIA
    {
        public int CODAUD { get; set; }
        public string PERAUD { get; set; }
        public string INDCUMCAPAUDAUD { get; set; }
        public string INDCUMCAPMINHORAUD { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODPRO { get; set; }
        public Nullable<int> CODSERAUD { get; set; }
        public Nullable<System.DateTime> FECINIAUDITORIA { get; set; }
        public Nullable<System.DateTime> FECFINAUDITORIA { get; set; }
    
        public virtual SAF_PROPUESTA SAF_PROPUESTA { get; set; }
    }
}
