//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_WORKFLOW
    {
        public int CODWORFLO { get; set; }
        public string TIPDOC { get; set; }
        public Nullable<int> CODDOC { get; set; }
        public string DESTIPDOC { get; set; }
        public Nullable<int> TIPCARUSU { get; set; }
        public string NOTWORFLO { get; set; }
        public Nullable<int> ESTWORFLO { get; set; }
        public Nullable<int> CODUSUSOL { get; set; }
        public Nullable<int> CODWORFLOPAR { get; set; }
        public string FLGNOTREP { get; set; }
        public string ESTREG { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
    }
}
