//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_SERAUDCARGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAF_SERAUDCARGO()
        {
            this.SAF_SERAUDCARCAP = new HashSet<SAF_SERAUDCARCAP>();
            this.SAF_SERAUDCAREXP = new HashSet<SAF_SERAUDCAREXP>();
        }
    
        public int CODSERAUDCAR { get; set; }
        public Nullable<int> NUMMININTSERAUDCAR { get; set; }
        public Nullable<int> NUMMINHORPARSERAUDCAR { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODSERAUD { get; set; }
        public Nullable<int> CODCAR { get; set; }
    
        public virtual SAF_CARGO SAF_CARGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAF_SERAUDCARCAP> SAF_SERAUDCARCAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAF_SERAUDCAREXP> SAF_SERAUDCAREXP { get; set; }
        public virtual SAF_SERVICIOAUDITORIA SAF_SERVICIOAUDITORIA { get; set; }
    }
}
