//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_PENALIDAD_PROPUESTA
    {
        public int CODPENAPRO { get; set; }
        public Nullable<int> CODPROP { get; set; }
        public Nullable<int> CODPENALIDAD { get; set; }
        public Nullable<decimal> PUNTOSCONTRA { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<System.DateTime> FECPENALIDAD { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODSOA { get; set; }
        public Nullable<int> CODPUB { get; set; }
        public Nullable<int> CODBAS { get; set; }
    }
}
