//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_SOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAF_SOA()
        {
            this.SAF_CONSULTA = new HashSet<SAF_CONSULTA>();
            this.SAF_INVITACION = new HashSet<SAF_INVITACION>();
            this.SAF_PROPUESTA = new HashSet<SAF_PROPUESTA>();
            this.SAF_SOLICITUD = new HashSet<SAF_SOLICITUD>();
        }
    
        public int CODSOA { get; set; }
        public string RAZSOCSOA { get; set; }
        public string RUCSOA { get; set; }
        public string NOMREPLEGSOA { get; set; }
        public string APEREPLEGSOA { get; set; }
        public string CORREPLEGSOA { get; set; }
        public string CELREPLEGSOA { get; set; }
        public string TELREPLEGSOA { get; set; }
        public string CODCOLCONSOA { get; set; }
        public string NUMPARSUNARPSOA { get; set; }
        public string FIRPCAOBSOA { get; set; }
        public string FIRINTSOA { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
        public string MISSOA { get; set; }
        public string VISSOA { get; set; }
        public byte[] ARCCOLCONSOA { get; set; }
        public string NOMUSU { get; set; }
        public string PASUSU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAF_CONSULTA> SAF_CONSULTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAF_INVITACION> SAF_INVITACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAF_PROPUESTA> SAF_PROPUESTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAF_SOLICITUD> SAF_SOLICITUD { get; set; }
    }
}
