//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_CORTE_AUDITOR
    {
        public int CODCORAUD { get; set; }
        public Nullable<int> EXPHORAUDFIN { get; set; }
        public Nullable<int> EXPHORGESPUB { get; set; }
        public Nullable<int> CAPAHORAUDFIN { get; set; }
        public Nullable<int> CAPAHORGESPUB { get; set; }
        public Nullable<int> EXPPUNT { get; set; }
        public Nullable<int> CAPAPUNT { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODAUD { get; set; }
        public Nullable<int> CODPUB { get; set; }
        public Nullable<int> TOTALPUNT { get; set; }
    
        public virtual SAF_AUDITOR SAF_AUDITOR { get; set; }
        public virtual SAF_PUBLICACION SAF_PUBLICACION { get; set; }
    }
}
