//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_CRONOENTIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAF_CRONOENTIDAD()
        {
            this.SAF_BASE = new HashSet<SAF_BASE>();
        }
    
        public int CODCROENT { get; set; }
        public Nullable<System.DateTime> FECINICROENT { get; set; }
        public Nullable<System.DateTime> FECFINCROENT { get; set; }
        public Nullable<int> TIPCONTCROENT { get; set; }
        public Nullable<int> TIPENTCROENT { get; set; }
        public string DESCROENT { get; set; }
        public Nullable<int> CODENT { get; set; }
        public Nullable<int> CODCRO { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAF_BASE> SAF_BASE { get; set; }
        public virtual SAF_CRONOGRAMA SAF_CRONOGRAMA { get; set; }
        public virtual SAF_ENTIDADES SAF_ENTIDADES { get; set; }
    }
}
