//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_WORKFLOW
    {
        public int CODWORFLO { get; set; }
        public string TIPDOC { get; set; }
        public Nullable<int> CODDOC { get; set; }
        public string DESTIPDOC { get; set; }
        public Nullable<int> TIPCARUSU { get; set; }
        public string NOTWORFLO { get; set; }
        public Nullable<int> ESTWORFLO { get; set; }
        public Nullable<int> CODUSUSOL { get; set; }
        public Nullable<int> CODWORFLOPAR { get; set; }
        public string FLGNOTREP { get; set; }
        public string ESTREG { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
    }
}
