//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_ENTIDADES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAF_ENTIDADES()
        {
            this.SAF_CRONOENTIDAD = new HashSet<SAF_CRONOENTIDAD>();
        }
    
        public int CODENT { get; set; }
        public string RAZSOCENT { get; set; }
        public string RUCENT { get; set; }
        public string VISENT { get; set; }
        public string MISENT { get; set; }
        public string ACTPRIENT { get; set; }
        public string BASLEGENT { get; set; }
        public byte[] ORGENT { get; set; }
        public string DOMLEGENT { get; set; }
        public string CODDEPENT { get; set; }
        public string CODPROENT { get; set; }
        public string CODDISENT { get; set; }
        public string PAGWEBENT { get; set; }
        public string NOMREPLEGENT { get; set; }
        public string APEREPLEGENT { get; set; }
        public string CORREPLEGENT { get; set; }
        public string TELREPLEGENT { get; set; }
        public string CELREPLEGENT { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAF_CRONOENTIDAD> SAF_CRONOENTIDAD { get; set; }
    }
}
