//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAF_FLUJO_DOCUMENTO
    {
        public int CODFLUDOC { get; set; }
        public Nullable<System.DateTime> FECENVFLUDOC { get; set; }
        public Nullable<System.DateTime> FECRECFLUDOC { get; set; }
        public string USUENVFLUDOC { get; set; }
        public string USURECFLUDOC { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> CODDOC { get; set; }
        public string NUMFLUDOC { get; set; }
        public string OBSFLUDOC { get; set; }
    
        public virtual SAF_DOCUMENTO SAF_DOCUMENTO { get; set; }
    }
}
