//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    
    public partial class SP_SAF_BASE_RPT_Result1
    {
        public string Column1 { get; set; }
        public string NUMBAS { get; set; }
        public string FECMAXCREPUBBAS { get; set; }
        public string ANIOCRO { get; set; }
        public string DESBAS { get; set; }
        public string TOTRETECOBAS { get; set; }
        public string TOTVIABAS { get; set; }
        public string FIRPCAOBBAS { get; set; }
        public string FIRINTBAS { get; set; }
    }
}
