//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    
    public partial class TcAUDITORIAS
    {
        public Nullable<int> CODPRO { get; set; }
        public int CODAUDITORIA { get; set; }
        public string PERAUD { get; set; }
        public string DESBAS { get; set; }
    }
}
