//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    
    public partial class TcAUDITORIAS
    {
        public Nullable<int> CODPRO { get; set; }
        public int CODAUDITORIA { get; set; }
        public string PERAUD { get; set; }
        public string DESBAS { get; set; }
    }
}
