//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    
    public partial class TcDETALLEEQUIPOPORAUDITORIA
    {
        public int CODAUDITORIA { get; set; }
        public int CODAUD { get; set; }
        public int CODPROEQU { get; set; }
        public string NOMCOMAUD { get; set; }
        public Nullable<System.DateTime> FECPROEQUIDET { get; set; }
        public string NOMCAR { get; set; }
    }
}
