//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    
    public partial class TcEQUIPOAUDITORIA
    {
        public int CODPROEQU { get; set; }
        public Nullable<int> CODINV { get; set; }
        public int CODAUD { get; set; }
        public string NOMCOMAUD { get; set; }
        public string DNIAUD { get; set; }
        public string CELAUD { get; set; }
        public string CORAUD { get; set; }
        public string NOMCAR { get; set; }
        public string PERAUD { get; set; }
    }
}
