//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    
    public partial class TcMENUPORPERFIL
    {
        public int CODMEN { get; set; }
        public Nullable<int> CODPER { get; set; }
        public string DESMEN { get; set; }
        public string RUTAMEN { get; set; }
        public string ICONCSS { get; set; }
        public string ESTREG { get; set; }
    }
}
