//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    
    public partial class TcPROPUESTARPT
    {
        public int CODPRO { get; set; }
        public string NUMPRO { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public string DESBAS { get; set; }
        public Nullable<int> CODPUB { get; set; }
        public string NUMPUB { get; set; }
        public int CODSOA { get; set; }
        public string RUCSOA { get; set; }
        public string RAZSOCSOA { get; set; }
        public Nullable<decimal> RETRECO { get; set; }
        public Nullable<decimal> IGVTOTAL { get; set; }
        public Nullable<decimal> RETRECOTOTAL { get; set; }
        public Nullable<decimal> MONTVIATICO { get; set; }
    }
}
