//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    
    public partial class TcPROPUESTAS
    {
        public Nullable<int> CODPUB { get; set; }
        public int CODPRO { get; set; }
        public Nullable<int> CODSOA { get; set; }
        public string RUCSOA { get; set; }
        public string RAZSOCSOA { get; set; }
        public string NOMREPLEGSOA { get; set; }
        public string CELREPLEGSOA { get; set; }
        public string CORREPLEGSOA { get; set; }
        public string DESBAS { get; set; }
        public decimal RETRECOTOTAL { get; set; }
        public decimal IGVTOTAL { get; set; }
        public decimal MONTVIATICO { get; set; }
        public decimal RETRECO { get; set; }
        public Nullable<int> ESTPROP { get; set; }
        public Nullable<long> CODARCFIRINT { get; set; }
        public Nullable<long> CODARCFIRPCAOB { get; set; }
        public string NOMBLABELFIRINT { get; set; }
        public string NOMBLABELFIRPCAOB { get; set; }
        public string INDREQFIRINT { get; set; }
        public string INDREQFIRPCAOB { get; set; }
        public decimal TOTRETECOBASREQ { get; set; }
        public decimal TOTIGVBASREQ { get; set; }
        public decimal TOTVIABASREQ { get; set; }
        public string VALOR { get; set; }
        public Nullable<int> PUNTAJETOTAL { get; set; }
    }
}
