//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    
    public partial class TcRESULTADOCORTE
    {
        public Nullable<int> CODAUD { get; set; }
        public string NOMCOMAUD { get; set; }
        public string NOMCAR { get; set; }
        public Nullable<int> CODCAR { get; set; }
        public Nullable<int> EXPHORAUDFIN { get; set; }
        public Nullable<int> EXPHORGESPUB { get; set; }
        public Nullable<int> CAPAHORAUDFIN { get; set; }
        public Nullable<int> CAPAHORGESPUB { get; set; }
        public Nullable<int> EXPPUNT { get; set; }
        public Nullable<int> CAPAPUNT { get; set; }
        public Nullable<int> TOTALPUNT { get; set; }
    }
}
