//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    
    public partial class TcSAFPUBLICACIONBASERPT
    {
        public string CODPUBBAS { get; set; }
        public string CODPUB { get; set; }
        public string CODBAS { get; set; }
        public string DESPUBBAS { get; set; }
    }
}
