//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    
    public partial class TcSAFBASERPT
    {
        public string NUMBAS { get; set; }
        public string FECMAXCREPUBBAS { get; set; }
        public string ANIOCRO { get; set; }
        public string DESBAS { get; set; }
        public string TOTRETECOBAS { get; set; }
        public string TOTVIABAS { get; set; }
        public string FIRPCAOBBAS { get; set; }
        public string FIRINTBAS { get; set; }
        public string CODBAS { get; set; }
    }
}
