//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    
    public partial class TcSAFPUBLICACIONRPT
    {
        public string ANIOCRO { get; set; }
        public string NUMPUB { get; set; }
        public string FECMAXCONS { get; set; }
        public string FECMAXCRECON { get; set; }
        public string FECMAXRESCONS { get; set; }
        public string FECMAXPREPROP { get; set; }
    }
}
