//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    
    public partial class TcSAFCRONOGRAMARPT
    {
        public string CODCRO { get; set; }
        public string ANIOCRO { get; set; }
        public string FECPUBCRO { get; set; }
        public string FECMAXCREBASCRO { get; set; }
    }
}
