//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    
    public partial class TcSUBMENUPORMENU
    {
        public int CODSUBMEN { get; set; }
        public string DESSUBMEN { get; set; }
        public string RUTASUBMEN { get; set; }
        public Nullable<int> CODMEN { get; set; }
    }
}
