//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SAF_PARAMETRICA
    {
        public int CODPAR { get; set; }
        public string NOMPAR { get; set; }
        public string VALOR { get; set; }
        public Nullable<int> CODTIPPAR { get; set; }
        public string NOMTIPPAR { get; set; }
    }
}
