//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SAF_CARGOSENSERVICIO
    {
        public Nullable<int> CODBAS { get; set; }
        public Nullable<int> CODSERAUD { get; set; }
        public int CODSERAUDCAR { get; set; }
        public int CODCAR { get; set; }
        public string NOMCAR { get; set; }
        public Nullable<int> NUMMINHORPARSERAUDCAR { get; set; }
        public Nullable<int> NUMMININTSERAUDCAR { get; set; }
        public Nullable<int> NUMMINHORSERAUDCAREXP { get; set; }
        public Nullable<int> NUMMINHORSERAUDCAPCAP { get; set; }
    }
}
