//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SAF_PROPUESTAEJECUCION
    {
        public int CODPRO { get; set; }
        public int CODAUD { get; set; }
        public string PERAUD { get; set; }
        public Nullable<int> CODSOA { get; set; }
        public int CODPUB { get; set; }
        public string DESBAS { get; set; }
    }
}
