//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SAF_INVITACION
    {
        public int CODINV { get; set; }
        public Nullable<int> ESTINV { get; set; }
        public string VALOR { get; set; }
        public string FECACEPINV { get; set; }
        public string FECMAXPREPROINV { get; set; }
        public string NUMINV { get; set; }
        public Nullable<int> CODPUB { get; set; }
        public Nullable<int> CODSERAUD { get; set; }
        public int CODAUD { get; set; }
        public string NOMCOMAUD { get; set; }
        public string DNIAUD { get; set; }
        public int CODSOA { get; set; }
        public string RAZSOCSOA { get; set; }
    }
}
