//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SAF_AUDITORIAEQUIPO
    {
        public int CODPROEQU { get; set; }
        public Nullable<int> CODAUD { get; set; }
        public Nullable<int> CODCAR { get; set; }
        public Nullable<int> CODAUDITORIA { get; set; }
        public string NOMCOMAUD { get; set; }
        public string NOMCAR { get; set; }
    }
}
