//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SAF_PUBLICACIONBASE
    {
        public int CODPUB { get; set; }
        public string NUMPUB { get; set; }
        public Nullable<int> ESTPUB { get; set; }
        public int CODBAS { get; set; }
        public Nullable<int> CODCRO { get; set; }
        public Nullable<int> CODCROENT { get; set; }
        public string DESBAS { get; set; }
        public string ESTREG { get; set; }
    }
}
