//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SAF_CRONOGRAMA
    {
        public int CODCRO { get; set; }
        public Nullable<int> ANIOCRO { get; set; }
        public Nullable<System.DateTime> FECPUBCRO { get; set; }
        public Nullable<System.DateTime> FECMAXCREBASCRO { get; set; }
        public Nullable<int> NUMREPCRO { get; set; }
        public Nullable<System.DateTime> FECREG { get; set; }
        public Nullable<System.DateTime> FECMOD { get; set; }
        public string USUREG { get; set; }
        public string USUMOD { get; set; }
        public string ESTREG { get; set; }
        public Nullable<int> ESTCRO { get; set; }
        public Nullable<int> NUMBAS { get; set; }
        public Nullable<int> NUMPUB { get; set; }
        public int CODPAR { get; set; }
        public string NOMPAR { get; set; }
    }
}
