//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SAF_WORKFLOW
    {
        public int CODWORFLO { get; set; }
        public string CODTIPDOC { get; set; }
        public Nullable<int> CODDOC { get; set; }
        public Nullable<int> CODESTDOC { get; set; }
        public string DESESTDOC { get; set; }
        public string DESTIPDOC { get; set; }
        public Nullable<int> TIPCARUSU { get; set; }
        public string NOTWORFLO { get; set; }
        public Nullable<int> ESTWORFLO { get; set; }
        public Nullable<int> CODWORFLOPAR { get; set; }
        public string FLGNOTREP { get; set; }
        public Nullable<int> CODUSUSOL { get; set; }
        public string NOMUSU { get; set; }
        public string NOMBRECOMPUSU { get; set; }
        public Nullable<int> CODTIPCARUSU { get; set; }
        public string DESTIPCARUSU { get; set; }
    }
}
