//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOCAUD.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SAF_PERFILMENU
    {
        public int CODPERMEN { get; set; }
        public int CODPER { get; set; }
        public int CODMEN { get; set; }
        public string DESPER { get; set; }
        public string DESMEN { get; set; }
        public string NOMPER { get; set; }
    }
}
